"""Persistent, source-attributed prompt/video style library."""

from __future__ import annotations

import copy
import json
import math
import os
import re
import shutil
import subprocess
import threading
import time
import uuid
from concurrent.futures import FIRST_COMPLETED, Future, ThreadPoolExecutor, wait
from pathlib import Path
from typing import Any


MINIMAX_H3_1K_SOURCE = {
    "id": "huggingface:ostris/minimax_h3_1k",
    "type": "huggingface_dataset",
    "author": "ostris",
    "name": "MiniMax H3 - 1K",
    "url": "https://huggingface.co/datasets/ostris/minimax_h3_1k",
    "repoId": "ostris/minimax_h3_1k",
    "modelFamily": "minimax",
    "collection": "MiniMax H3 1K",
    "license": None,
    "licenseNotice": "No license is specified in the dataset card.",
    "description": (
        "1,000 MiniMax H3 capability samples at 768-base resolution, "
        "generated by the source author with 30 steps."
    ),
    "expectedStyles": 1000,
    "expectedBytes": 1_432_969_644,
}

_STYLE_ID = re.compile(r"minimax-h3-1k-(\d{6})$")
MAX_MANIFEST_BACKUPS = 10
MIN_IMPORT_MARGIN_BYTES = 512 * 1024 * 1024
IMPORT_MARGIN_RATIO = 0.15
ACTIVE_IMPORT_STATUSES = {"queued", "running", "cancelling"}
RESUMABLE_IMPORT_STATUSES = {"cancelled", "failed", "interrupted"}
STYLE_LIBRARY_DIR_ENV = "MAESTRO_STYLE_LIBRARY_DIR"


class StyleManifestDegradedError(RuntimeError):
    """Raised when writes are blocked until a corrupt manifest is recovered."""


class StyleImportPreflightError(RuntimeError):
    """Raised before a worker starts when durable storage cannot fit the import."""

    def __init__(
        self,
        message: str,
        *,
        required_bytes: int,
        free_bytes: int,
        remaining_bytes: int,
        margin_bytes: int,
        storage_path: Path,
    ) -> None:
        super().__init__(message)
        self.required_bytes = int(required_bytes)
        self.free_bytes = int(free_bytes)
        self.remaining_bytes = int(remaining_bytes)
        self.margin_bytes = int(margin_bytes)
        self.storage_path = storage_path

    def detail(self) -> dict[str, Any]:
        return {
            "code": "style_import_insufficient_storage",
            "message": str(self),
            "requiredBytes": self.required_bytes,
            "freeBytes": self.free_bytes,
            "remainingBytes": self.remaining_bytes,
            "marginBytes": self.margin_bytes,
            "storagePath": str(self.storage_path),
        }


class _StyleImportCancelled(RuntimeError):
    """Internal cooperative-cancellation signal for a style import worker."""


def resolve_style_library_root(app_dir: str | os.PathLike[str]) -> Path:
    """Resolve configurable storage outside the application source directory."""
    app_path = Path(app_dir).expanduser().resolve()
    configured = str(os.environ.get(STYLE_LIBRARY_DIR_ENV) or "").strip()
    if configured:
        configured_path = Path(configured).expanduser()
        if not configured_path.is_absolute():
            configured_path = app_path.parent / configured_path
        return configured_path.resolve()

    project_root = app_path.parent
    pinokio_home = str(os.environ.get("PINOKIO_HOME") or "").strip()
    if pinokio_home:
        return (Path(pinokio_home).expanduser().resolve() / "cache" / "maestro" / "style-library")
    if project_root.parent.name in {"api", "plugin"}:
        return (project_root.parent.parent / "cache" / "maestro" / "style-library").resolve()
    return (project_root / ".maestro-data" / "style-library").resolve()


def migrate_legacy_style_library(
    legacy_root: str | os.PathLike[str],
    durable_root: str | os.PathLike[str],
) -> tuple[Path, str | None]:
    """Atomically relocate legacy data when both roots share a filesystem."""
    legacy = Path(legacy_root).expanduser().resolve()
    durable = Path(durable_root).expanduser().resolve()
    if legacy == durable or not legacy.exists() or durable.exists():
        return durable, None
    durable.parent.mkdir(parents=True, exist_ok=True)
    try:
        os.replace(legacy, durable)
    except OSError as exc:
        return legacy, (
            f"Could not atomically migrate style storage to {durable}; "
            f"continuing at legacy path {legacy}: {exc}"
        )
    return durable, f"Style storage migrated atomically from {legacy} to {durable}."


def _atomic_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")
    temporary.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    os.replace(temporary, path)


def _directory_stats(directory: Path) -> tuple[int, int]:
    files = 0
    size = 0
    if not directory.is_dir():
        return files, size
    for entry in directory.iterdir():
        try:
            if entry.is_file() and entry.suffix.lower() in {".mp4", ".txt"}:
                files += 1
                size += entry.stat().st_size
        except OSError:
            continue
    return files, size


class StyleLibrary:
    """Own style manifests, media, import jobs and deletion tombstones."""

    def __init__(self, root: str | os.PathLike[str], *, storage_notice: str | None = None) -> None:
        self.root = Path(root).expanduser().resolve()
        self.source_root = self.root / "minimax" / "ostris-minimax_h3_1k"
        self.raw_dir = self.source_root / "raw"
        self.preview_dir = self.source_root / "previews"
        self.manifest_path = self.source_root / "manifest.json"
        self.manifest_backup_dir = self.source_root / "manifest-backups"
        self.manifest_quarantine_dir = self.source_root / "manifest-quarantine"
        self.job_path = self.source_root / "import-job.json"
        self._lock = threading.RLock()
        self._jobs: dict[str, dict[str, Any]] = {}
        self._active_job_id: str | None = None
        self._cancel_events: dict[str, threading.Event] = {}
        self._manifest_error: str | None = None
        self._quarantined_manifest: str | None = None
        self.storage_notice = storage_notice
        self._recover_job()

    def _recover_job(self) -> None:
        if not self.job_path.is_file():
            return
        try:
            job = json.loads(self.job_path.read_text(encoding="utf-8"))
        except (OSError, ValueError, json.JSONDecodeError):
            return
        if not isinstance(job, dict) or not job.get("jobId"):
            return
        if job.get("status") in ACTIVE_IMPORT_STATUSES:
            job.update({
                "status": "interrupted",
                "stage": "interrupted",
                "message": "Import interrupted; press download again to resume.",
                "resumeAvailable": True,
                "updatedAt": time.time(),
                "finishedAt": time.time(),
            })
            _atomic_json(self.job_path, job)
        self._jobs[str(job["jobId"])] = job

    @staticmethod
    def _empty_manifest() -> dict[str, Any]:
        return {
            "version": 1,
            "source": copy.deepcopy(MINIMAX_H3_1K_SOURCE),
            "styles": [],
            "deletedIds": [],
            "updatedAt": None,
        }

    @staticmethod
    def _validate_manifest(payload: Any) -> dict[str, Any]:
        if not isinstance(payload, dict):
            raise ValueError("Style manifest must be an object")
        if not isinstance(payload.get("styles"), list):
            raise ValueError("Style manifest styles must be a list")
        if not isinstance(payload.get("deletedIds"), list):
            raise ValueError("Style manifest deletedIds must be a list")
        if not isinstance(payload.get("source"), dict):
            raise ValueError("Style manifest source must be an object")
        return payload

    def _valid_backups(self) -> list[tuple[Path, dict[str, Any]]]:
        if not self.manifest_backup_dir.is_dir():
            return []
        backups: list[tuple[Path, dict[str, Any]]] = []
        for path in sorted(self.manifest_backup_dir.glob("manifest-*.json"), reverse=True):
            try:
                payload = self._validate_manifest(json.loads(path.read_text(encoding="utf-8")))
            except (OSError, ValueError, json.JSONDecodeError):
                continue
            backups.append((path, payload))
        return backups

    def _quarantine_corrupt_manifest(self, error: Exception) -> dict[str, Any] | None:
        self._manifest_error = str(error)
        if self._quarantined_manifest is None and self.manifest_path.is_file():
            try:
                self.manifest_quarantine_dir.mkdir(parents=True, exist_ok=True)
                destination = self.manifest_quarantine_dir / (
                    f"manifest-{time.time_ns()}-{uuid.uuid4().hex[:8]}.corrupt.json"
                )
                shutil.copy2(self.manifest_path, destination)
                self._quarantined_manifest = destination.name
            except OSError:
                self._quarantined_manifest = "quarantine-copy-failed"
        backups = self._valid_backups()
        return copy.deepcopy(backups[0][1]) if backups else None

    def _manifest(self) -> dict[str, Any]:
        if not self.manifest_path.is_file():
            self._manifest_error = None
            self._quarantined_manifest = None
            return self._empty_manifest()
        try:
            payload = self._validate_manifest(
                json.loads(self.manifest_path.read_text(encoding="utf-8")),
            )
        except (OSError, ValueError, json.JSONDecodeError) as exc:
            backup = self._quarantine_corrupt_manifest(exc)
            if backup is not None:
                return backup
            raise StyleManifestDegradedError(
                f"Style manifest is corrupt and no valid backup is available: {exc}"
            ) from exc
        self._manifest_error = None
        self._quarantined_manifest = None
        return payload

    def _require_writable_manifest(self) -> dict[str, Any]:
        manifest = self._manifest()
        if self._manifest_error:
            raise StyleManifestDegradedError(
                "Style manifest is degraded; recover its backup before importing or deleting styles"
            )
        return manifest

    def _write_manifest(self, payload: dict[str, Any]) -> None:
        self._require_writable_manifest()
        valid = self._validate_manifest(copy.deepcopy(payload))
        self.manifest_backup_dir.mkdir(parents=True, exist_ok=True)
        backup = self.manifest_backup_dir / (
            f"manifest-{time.time_ns()}-{uuid.uuid4().hex[:8]}.json"
        )
        _atomic_json(backup, valid)
        _atomic_json(self.manifest_path, valid)
        for stale, _ in self._valid_backups()[MAX_MANIFEST_BACKUPS:]:
            try:
                stale.unlink()
            except OSError:
                pass

    def recover_manifest(self) -> dict[str, Any]:
        """Explicitly restore the newest valid generation after quarantine."""
        with self._lock:
            try:
                self._manifest()
            except StyleManifestDegradedError:
                pass
            if not self._manifest_error:
                return {"recovered": False, "status": "healthy", "message": "Manifest is already healthy"}
            backups = self._valid_backups()
            if not backups:
                raise StyleManifestDegradedError("No valid style manifest backup is available")
            backup_path, payload = backups[0]
            _atomic_json(self.manifest_path, payload)
            self._manifest_error = None
            quarantine = self._quarantined_manifest
            self._quarantined_manifest = None
            return {
                "recovered": True,
                "status": "healthy",
                "backup": backup_path.name,
                "quarantine": quarantine,
                "deletedIds": copy.deepcopy(payload.get("deletedIds") or []),
            }

    def source_status(self) -> list[dict[str, Any]]:
        with self._lock:
            try:
                manifest = self._manifest()
            except StyleManifestDegradedError:
                manifest = self._empty_manifest()
            deleted = set(manifest.get("deletedIds") or [])
            styles = [
                item for item in manifest.get("styles", [])
                if isinstance(item, dict) and item.get("id") not in deleted
            ]
            files, downloaded_bytes = _directory_stats(self.raw_dir)
            active = self._jobs.get(self._active_job_id or "")
            source = copy.deepcopy(MINIMAX_H3_1K_SOURCE)
            source.update({
                "revision": (manifest.get("source") or {}).get("revision"),
                "lastModified": (manifest.get("source") or {}).get("lastModified"),
                "installed": bool(styles),
                "styleCount": len(styles),
                "downloadedFiles": files,
                "downloadedBytes": downloaded_bytes,
                "activeJob": copy.deepcopy(active) if active else None,
                "latestJob": copy.deepcopy(next(reversed(self._jobs.values()), None)),
                "storagePath": str(self.root),
                "storageNotice": self.storage_notice,
                "status": "degraded" if self._manifest_error else "healthy",
                "degraded": bool(self._manifest_error),
                "manifestError": self._manifest_error,
                "recoveryAvailable": bool(self._valid_backups()),
                "quarantine": self._quarantined_manifest,
            })
            return [source]

    def list_styles(
        self,
        *,
        model_family: str = "minimax",
        source_id: str = "",
        collection: str = "",
        group: str = "",
        query: str = "",
        sort: str = "source_order",
        offset: int = 0,
        limit: int = 60,
    ) -> dict[str, Any]:
        with self._lock:
            manifest = self._manifest()
        deleted = set(manifest.get("deletedIds") or [])
        items = [
            copy.deepcopy(item)
            for item in manifest.get("styles", [])
            if isinstance(item, dict) and item.get("id") not in deleted
        ]
        if model_family:
            items = [item for item in items if item.get("modelFamily") == model_family]
        if source_id:
            items = [item for item in items if (item.get("source") or {}).get("id") == source_id]
        if collection:
            items = [item for item in items if item.get("collection") == collection]
        if group:
            items = [item for item in items if item.get("group") == group]
        needle = query.strip().casefold()
        if needle:
            items = [
                item for item in items
                if needle in str(item.get("prompt") or "").casefold()
                or needle in str(item.get("title") or "").casefold()
                or any(needle in str(tag).casefold() for tag in item.get("tags") or [])
            ]
        if sort == "prompt_asc":
            items.sort(key=lambda item: str(item.get("prompt") or "").casefold())
        elif sort == "prompt_desc":
            items.sort(key=lambda item: str(item.get("prompt") or "").casefold(), reverse=True)
        elif sort == "newest":
            items.sort(key=lambda item: float(item.get("importedAt") or 0), reverse=True)
        elif sort == "oldest":
            items.sort(key=lambda item: float(item.get("importedAt") or 0))
        else:
            items.sort(key=lambda item: int(item.get("sourceOrder") or 0))
        total = len(items)
        offset = max(0, int(offset))
        limit = min(200, max(1, int(limit)))
        page = items[offset:offset + limit]
        for item in page:
            style_id = str(item["id"])
            item["previewUrl"] = f"/api/v1/style-library/styles/{style_id}/preview"
            item["videoUrl"] = f"/api/v1/style-library/styles/{style_id}/video"
        facets = {
            "sources": sorted({
                str((item.get("source") or {}).get("id") or "")
                for item in items if (item.get("source") or {}).get("id")
            }),
            "collections": sorted({str(item.get("collection")) for item in items if item.get("collection")}),
            "groups": sorted({str(item.get("group")) for item in items if item.get("group")}),
        }
        return {
            "styles": page,
            "total": total,
            "offset": offset,
            "limit": limit,
            "facets": facets,
            "status": "degraded" if self._manifest_error else "healthy",
        }

    def import_preflight(self, *, reject_if_insufficient: bool = False) -> dict[str, Any]:
        """Return the storage budget without creating directories or a worker."""
        files, downloaded_bytes = _directory_stats(self.raw_dir)
        expected_bytes = int(MINIMAX_H3_1K_SOURCE["expectedBytes"])
        remaining_bytes = max(0, expected_bytes - downloaded_bytes)
        margin_bytes = max(
            MIN_IMPORT_MARGIN_BYTES,
            int(math.ceil(expected_bytes * IMPORT_MARGIN_RATIO)),
        )
        required_bytes = remaining_bytes + margin_bytes
        probe = self.root
        while not probe.exists() and probe.parent != probe:
            probe = probe.parent
        usage = shutil.disk_usage(probe)
        result = {
            "storagePath": str(self.root),
            "probePath": str(probe),
            "downloadedFiles": files,
            "downloadedBytes": downloaded_bytes,
            "expectedBytes": expected_bytes,
            "remainingBytes": remaining_bytes,
            "marginBytes": margin_bytes,
            "requiredBytes": required_bytes,
            "freeBytes": int(usage.free),
            "sufficient": int(usage.free) >= required_bytes,
        }
        if reject_if_insufficient and not result["sufficient"]:
            raise StyleImportPreflightError(
                "Not enough free storage for the MiniMax style import and safety margin",
                required_bytes=required_bytes,
                free_bytes=int(usage.free),
                remaining_bytes=remaining_bytes,
                margin_bytes=margin_bytes,
                storage_path=self.root,
            )
        return result

    def start_minimax_import(self) -> dict[str, Any]:
        with self._lock:
            self._require_writable_manifest()
            if self._active_job_id:
                active = self._jobs.get(self._active_job_id)
                if active and active.get("status") in ACTIVE_IMPORT_STATUSES:
                    return copy.deepcopy(active)
            preflight = self.import_preflight(reject_if_insufficient=True)
            previous = next(reversed(self._jobs.values()), None)
            resumable = bool(previous and previous.get("status") in RESUMABLE_IMPORT_STATUSES)
            job_id = (
                str(previous["jobId"])
                if resumable
                else f"style-import-{uuid.uuid4().hex[:12]}"
            )
            now = time.time()
            job = copy.deepcopy(previous) if resumable else {}
            job.update({
                "jobId": job_id,
                "status": "queued",
                "stage": "queued",
                "current": 0,
                "total": int(MINIMAX_H3_1K_SOURCE["expectedStyles"]),
                "message": (
                    "Resuming the partial MiniMax H3 style download…"
                    if resumable else "Preparing MiniMax H3 style download…"
                ),
                "downloadedBytes": int(preflight["downloadedBytes"]),
                "expectedBytes": int(MINIMAX_H3_1K_SOURCE["expectedBytes"]),
                "storagePath": str(self.root),
                "preflight": preflight,
                "error": None,
                "createdAt": float(job.get("createdAt") or now),
                "updatedAt": now,
                "finishedAt": None,
                "cancelRequestedAt": None,
                "resumeAvailable": False,
                "resumed": resumable,
                "resumeCount": int(job.get("resumeCount") or 0) + (1 if resumable else 0),
                "source": copy.deepcopy(MINIMAX_H3_1K_SOURCE),
            })
            self._jobs[job_id] = job
            self._active_job_id = job_id
            self._cancel_events[job_id] = threading.Event()
            _atomic_json(self.job_path, job)
            thread = threading.Thread(
                target=self._run_minimax_import,
                args=(job_id,),
                name=f"style-import-{job_id[-6:]}",
                daemon=True,
            )
            thread.start()
            return copy.deepcopy(job)

    def cancel_import(self, job_id: str) -> dict[str, Any] | None:
        with self._lock:
            job = self._jobs.get(job_id)
            if not job:
                return None
            if job.get("status") not in ACTIVE_IMPORT_STATUSES:
                return copy.deepcopy(job)
            cancel_event = self._cancel_events.setdefault(job_id, threading.Event())
            cancel_event.set()
            job.update({
                "status": "cancelling",
                "message": "Cancelling safely; partial files will be kept for resume…",
                "cancelRequestedAt": time.time(),
                "resumeAvailable": True,
                "updatedAt": time.time(),
            })
            snapshot = copy.deepcopy(job)
        _atomic_json(self.job_path, snapshot)
        return snapshot

    def import_status(self, job_id: str) -> dict[str, Any] | None:
        with self._lock:
            job = self._jobs.get(job_id)
            return copy.deepcopy(job) if job else None

    def _update_job(self, job_id: str, *, persist: bool = True, **patch: Any) -> None:
        with self._lock:
            job = self._jobs.get(job_id)
            if not job:
                return
            job.update(copy.deepcopy(patch))
            job["updatedAt"] = time.time()
            snapshot = copy.deepcopy(job)
        if persist:
            _atomic_json(self.job_path, snapshot)

    def _cancel_event(self, job_id: str) -> threading.Event:
        with self._lock:
            return self._cancel_events.setdefault(job_id, threading.Event())

    def _raise_if_cancelled(self, job_id: str, stage: str) -> None:
        if self._cancel_event(job_id).is_set():
            raise _StyleImportCancelled(f"Style import cancelled during {stage}")

    def _monitor_download(self, job_id: str, stop: threading.Event) -> None:
        while not stop.wait(1.0):
            if self._cancel_event(job_id).is_set():
                self._update_job(
                    job_id,
                    status="cancelling",
                    message="Stopping the current download safely; partial files will be kept…",
                )
                return
            files, downloaded_bytes = _directory_stats(self.raw_dir)
            total = int(MINIMAX_H3_1K_SOURCE["expectedStyles"])
            pairs = min(total, files // 2)
            self._update_job(
                job_id,
                persist=False,
                current=pairs,
                downloadedBytes=downloaded_bytes,
                message=f"Downloading style media… {pairs}/{total}",
            )

    @staticmethod
    def _cancel_aware_tqdm(cancel_event: threading.Event):
        from tqdm.auto import tqdm

        class CancelAwareTqdm(tqdm):
            def update(self, n=1):
                if cancel_event.is_set():
                    raise _StyleImportCancelled("Style import cancelled during download")
                return super().update(n)

        return CancelAwareTqdm

    def _dataset_info(self):
        from huggingface_hub import HfApi

        return HfApi().dataset_info(str(MINIMAX_H3_1K_SOURCE["repoId"]))

    def _download_dataset(
        self,
        *,
        revision: str,
        ignored: list[str],
        cancel_event: threading.Event,
    ) -> None:
        from huggingface_hub import snapshot_download

        snapshot_download(
            repo_id=str(MINIMAX_H3_1K_SOURCE["repoId"]),
            repo_type="dataset",
            revision=revision,
            local_dir=str(self.raw_dir),
            allow_patterns=["*.mp4", "*.txt", "README.md"],
            ignore_patterns=ignored or None,
            max_workers=4,
            tqdm_class=self._cancel_aware_tqdm(cancel_event),
        )

    def _run_minimax_import(self, job_id: str) -> None:
        monitor_stop = threading.Event()
        monitor: threading.Thread | None = None
        cancel_event = self._cancel_event(job_id)
        try:
            self._raise_if_cancelled(job_id, "startup")
            self.raw_dir.mkdir(parents=True, exist_ok=True)
            self.preview_dir.mkdir(parents=True, exist_ok=True)
            existing = self._require_writable_manifest()
            self._raise_if_cancelled(job_id, "startup")
            deleted_ids = set(existing.get("deletedIds") or [])
            ignored: list[str] = []
            for style_id in deleted_ids:
                match = _STYLE_ID.fullmatch(str(style_id))
                if match:
                    ignored.extend([f"{match.group(1)}.mp4", f"{match.group(1)}.txt"])

            self._update_job(
                job_id,
                status="running",
                stage="downloading",
                message="Downloading 1,000 prompts and videos from Hugging Face…",
            )
            monitor = threading.Thread(
                target=self._monitor_download,
                args=(job_id, monitor_stop),
                name=f"style-progress-{job_id[-6:]}",
                daemon=True,
            )
            monitor.start()
            info = self._dataset_info()
            self._raise_if_cancelled(job_id, "download")
            self._download_dataset(
                revision=str(info.sha),
                ignored=ignored,
                cancel_event=cancel_event,
            )
            self._raise_if_cancelled(job_id, "download")
            monitor_stop.set()
            if monitor:
                monitor.join(timeout=3)
            files, downloaded_bytes = _directory_stats(self.raw_dir)
            self._update_job(
                job_id,
                stage="indexing",
                current=0,
                downloadedBytes=downloaded_bytes,
                message="Indexing prompts and source metadata…",
            )

            imported_at = time.time()
            source = copy.deepcopy(MINIMAX_H3_1K_SOURCE)
            source.update({
                "revision": info.sha,
                "lastModified": info.last_modified.isoformat() if info.last_modified else None,
            })
            styles: list[dict[str, Any]] = []
            expected_styles = int(MINIMAX_H3_1K_SOURCE["expectedStyles"])
            for number in range(1, expected_styles + 1):
                self._raise_if_cancelled(job_id, "indexing")
                sample = f"{number:06d}"
                style_id = f"minimax-h3-1k-{sample}"
                if style_id in deleted_ids:
                    continue
                prompt_path = self.raw_dir / f"{sample}.txt"
                video_path = self.raw_dir / f"{sample}.mp4"
                if not prompt_path.is_file() or not video_path.is_file():
                    raise RuntimeError(f"Dataset sample {sample} is incomplete")
                prompt = prompt_path.read_text(encoding="utf-8").strip()
                styles.append({
                    "id": style_id,
                    "modelFamily": "minimax",
                    "title": f"MiniMax H3 sample {sample}",
                    "prompt": prompt,
                    "collection": str(source["collection"]),
                    "group": "Source dataset",
                    "tags": ["minimax-h3", "video", "reference-dataset"],
                    "sourceOrder": number,
                    "sourceFilename": f"{sample}.txt",
                    "videoFilename": f"{sample}.mp4",
                    "source": copy.deepcopy(source),
                    "importedAt": imported_at,
                })
                if number % 50 == 0:
                    self._update_job(
                        job_id,
                        persist=False,
                        current=number,
                        message=f"Indexing prompts… {number}/{expected_styles}",
                    )
            manifest = {
                "version": 1,
                "source": source,
                "styles": styles,
                "deletedIds": sorted(deleted_ids),
                "updatedAt": time.time(),
            }

            self._update_job(
                job_id,
                stage="previews",
                current=0,
                total=len(styles),
                message="Creating lightweight previews…",
            )
            preview_failures = self._create_previews(job_id, styles, cancel_event)
            self._raise_if_cancelled(job_id, "previews")
            # Publish only after every cancellable stage has reached a safe boundary.
            # A cancelled refresh therefore leaves the previous manifest untouched.
            self._write_manifest(manifest)
            warning = None
            if preview_failures:
                warning = (
                    f"{len(preview_failures)} previews could not be created; "
                    "their videos and prompts are still available."
                )
            self._update_job(
                job_id,
                status="completed",
                stage="completed",
                current=len(styles),
                total=len(styles),
                downloadedBytes=downloaded_bytes,
                previewFailures=len(preview_failures),
                warning=warning,
                finishedAt=time.time(),
                message=(
                    f"Imported {len(styles)} MiniMax H3 styles."
                    if not warning else f"Imported {len(styles)} styles with {warning}"
                ),
                resumeAvailable=False,
            )
        except Exception as exc:
            monitor_stop.set()
            if monitor:
                monitor.join(timeout=3)
            files, downloaded_bytes = _directory_stats(self.raw_dir)
            cancelled = cancel_event.is_set() or isinstance(exc, _StyleImportCancelled)
            if cancelled:
                self._update_job(
                    job_id,
                    status="cancelled",
                    stage="cancelled",
                    downloadedFiles=files,
                    downloadedBytes=downloaded_bytes,
                    error=None,
                    resumeAvailable=True,
                    finishedAt=time.time(),
                    message="Import cancelled. Partial files were preserved and can be resumed.",
                )
            else:
                self._update_job(
                    job_id,
                    status="failed",
                    stage="failed",
                    downloadedFiles=files,
                    downloadedBytes=downloaded_bytes,
                    error=str(exc),
                    resumeAvailable=True,
                    finishedAt=time.time(),
                    message=f"Style import failed: {exc}",
                )
        finally:
            monitor_stop.set()
            with self._lock:
                if self._active_job_id == job_id:
                    self._active_job_id = None
                self._cancel_events.pop(job_id, None)

    def _create_previews(
        self,
        job_id: str,
        styles: list[dict[str, Any]],
        cancel_event: threading.Event,
    ) -> list[str]:
        completed = 0
        preview_failures: list[str] = []
        iterator = iter(styles)
        pending: dict[Future[Path], str] = {}

        def submit_next(pool: ThreadPoolExecutor) -> bool:
            try:
                item = next(iterator)
            except StopIteration:
                return False
            future = pool.submit(self._ensure_preview_for, item, cancel_event)
            pending[future] = str(item["id"])
            return True

        pool = ThreadPoolExecutor(max_workers=2)
        try:
            submit_next(pool)
            submit_next(pool)
            while pending:
                self._raise_if_cancelled(job_id, "previews")
                done, _ = wait(tuple(pending), timeout=0.25, return_when=FIRST_COMPLETED)
                if not done:
                    continue
                for future in done:
                    style_id = pending.pop(future)
                    try:
                        future.result()
                    except _StyleImportCancelled:
                        raise
                    except Exception as exc:
                        preview_failures.append(f"{style_id}: {exc}")
                    completed += 1
                    if completed % 10 == 0 or completed == len(styles):
                        self._update_job(
                            job_id,
                            persist=completed % 50 == 0 or completed == len(styles),
                            current=completed,
                            previewFailures=len(preview_failures),
                            message=f"Creating lightweight previews… {completed}/{len(styles)}",
                        )
                    submit_next(pool)
        finally:
            for future in pending:
                future.cancel()
            pool.shutdown(wait=True, cancel_futures=True)
        return preview_failures

    def _style_record(self, style_id: str) -> dict[str, Any]:
        if not _STYLE_ID.fullmatch(style_id):
            raise KeyError(style_id)
        manifest = self._manifest()
        deleted = set(manifest.get("deletedIds") or [])
        if style_id in deleted:
            raise KeyError(style_id)
        record = next((
            item for item in manifest.get("styles", [])
            if isinstance(item, dict) and item.get("id") == style_id
        ), None)
        if not record:
            raise KeyError(style_id)
        return record

    @staticmethod
    def _run_preview_process(
        command: list[str],
        cancel_event: threading.Event | None,
    ) -> tuple[int, str]:
        process = subprocess.Popen(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        deadline = time.monotonic() + 90
        while process.poll() is None:
            if cancel_event is not None and cancel_event.wait(0.1):
                process.terminate()
                try:
                    process.wait(timeout=3)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait(timeout=3)
                raise _StyleImportCancelled("Style import cancelled during previews")
            if cancel_event is None:
                time.sleep(0.1)
            if time.monotonic() >= deadline:
                process.kill()
                _, stderr = process.communicate()
                return -1, (stderr or "FFmpeg preview timed out")
        _, stderr = process.communicate()
        return int(process.returncode or 0), stderr or ""

    def _ensure_preview_for(
        self,
        record: dict[str, Any],
        cancel_event: threading.Event | None = None,
    ) -> Path:
        style_id = str(record["id"])
        destination = self.preview_dir / f"{style_id}.jpg"
        if destination.is_file() and destination.stat().st_size > 0:
            return destination
        if cancel_event is not None and cancel_event.is_set():
            raise _StyleImportCancelled("Style import cancelled during previews")
        source = self.raw_dir / str(record["videoFilename"])
        if not source.is_file():
            raise FileNotFoundError(source)
        temporary = destination.with_name(f".{destination.name}.{uuid.uuid4().hex}.tmp.jpg")
        error = "FFmpeg preview failed"
        for seek_args in (("-ss", "0.1"), ()):
            command = [
                os.environ.get("FFMPEG_BINARY", "ffmpeg"),
                "-v", "error", "-y", *seek_args, "-i", str(source),
                "-map", "0:v:0", "-frames:v", "1",
                "-vf", "scale=320:180:force_original_aspect_ratio=decrease,pad=320:180:(ow-iw)/2:(oh-ih)/2:color=black",
                "-q:v", "6", str(temporary),
            ]
            try:
                returncode, stderr = self._run_preview_process(command, cancel_event)
            except _StyleImportCancelled:
                try:
                    temporary.unlink(missing_ok=True)
                except OSError:
                    pass
                raise
            if returncode == 0 and temporary.is_file() and temporary.stat().st_size > 0:
                os.replace(temporary, destination)
                return destination
            error = (stderr or error)[-800:]
            try:
                temporary.unlink(missing_ok=True)
            except OSError:
                pass
        raise RuntimeError(error)

    def preview_path(self, style_id: str) -> Path:
        with self._lock:
            record = self._style_record(style_id)
        return self._ensure_preview_for(record)

    def video_path(self, style_id: str) -> Path:
        with self._lock:
            record = self._style_record(style_id)
        path = self.raw_dir / str(record["videoFilename"])
        if not path.is_file():
            raise FileNotFoundError(path)
        return path

    def delete_style(self, style_id: str) -> dict[str, Any]:
        with self._lock:
            self._require_writable_manifest()
            record = self._style_record(style_id)
            manifest = self._manifest()
            deleted = set(manifest.get("deletedIds") or [])
            deleted.add(style_id)
            manifest["deletedIds"] = sorted(deleted)
            manifest["updatedAt"] = time.time()
            self._write_manifest(manifest)
            paths = [
                self.raw_dir / str(record.get("sourceFilename") or ""),
                self.raw_dir / str(record.get("videoFilename") or ""),
                self.preview_dir / f"{style_id}.jpg",
            ]
        removed = []
        for path in paths:
            try:
                if path.is_file():
                    path.unlink()
                    removed.append(path.name)
            except OSError:
                continue
        return {"id": style_id, "deleted": True, "removedFiles": removed}
