import type { AgentAction } from './agentActions'

export type AgentCapabilityRisk = 'read' | 'edit' | 'compute'

export interface AgentCapabilityDescriptor {
  type: AgentAction['type']
  title: string
  purpose: string
  useWhen: string
  risk: AgentCapabilityRisk
  parameters: string[]
}

/**
 * Canonical knowledge catalog for the embedded Wizard. Add a capability here
 * when its parser and executor become available. The system prompt and the
 * handoff documentation can then describe the same contract without teaching
 * the model a second, contradictory version of it.
 */
export const AGENT_CAPABILITIES: AgentCapabilityDescriptor[] = [
  {
    type: 'open_tab',
    title: 'Open an application section',
    purpose: 'Navigate to a real HocusPocus section through its store state.',
    useWhen: 'The user asks to go somewhere or opening a section materially helps the answer.',
    risk: 'read',
    parameters: ['tab'],
  },
  {
    type: 'prepare_video',
    title: 'Prepare Studio video',
    purpose: 'Open Studio → Video and fill a validated text-to-video form.',
    useWhen: 'The user asks to prepare, configure, show or generate a video.',
    risk: 'edit',
    parameters: ['prompt', 'model_type', 'duration_seconds', 'resolution', 'aspect_ratio', 'seed', 'output_count'],
  },
  {
    type: 'prepare_image',
    title: 'Prepare Studio image',
    purpose: 'Open Studio → Image and fill a validated text-to-image form.',
    useWhen: 'The user asks to prepare, configure, show or generate an image, photo or portrait.',
    risk: 'edit',
    parameters: ['prompt', 'model_type', 'resolution', 'aspect_ratio', 'seed', 'output_count'],
  },
  {
    type: 'prepare_audio',
    title: 'Prepare Studio audio',
    purpose: 'Open Studio → Audio and fill Speech, Music or SFX. The Audios gallery only displays finished files.',
    useWhen: 'The user asks to prepare or generate speech, music or a sound effect.',
    risk: 'edit',
    parameters: ['audio_sub_mode', 'prompt', 'duration_seconds', 'model_type', 'negative_prompt'],
  },
  {
    type: 'queue_sfx_pack',
    title: 'Queue a Studio SFX pack',
    purpose: 'Open Studio → Audio → SFX and submit several MMAudio one-shots to the canonical queue.',
    useWhen: 'The user explicitly asks to create or generate a pack of game sound effects.',
    risk: 'compute',
    parameters: ['sfx_clips', 'confirm', 'model_type', 'negative_prompt'],
  },
  {
    type: 'prepare_3d',
    title: 'Prepare Studio 3D',
    purpose: 'Open Studio → 3D (Hunyuan3D) and fill a text-to-mesh form. The 3D gallery only displays finished models.',
    useWhen: 'The user asks to prepare or generate a 3D object, mesh or Hunyuan3D asset.',
    risk: 'edit',
    parameters: ['prompt', 'model_type', 'preset', 'seed'],
  },
  {
    type: 'open_story_section',
    title: 'Open a Story Lab section',
    purpose: 'Open any real Story Lab section, including its visual assets, music, production and assembly views.',
    useWhen: 'The user asks for a specific part of Story Lab or that section helps explain the next step.',
    risk: 'read',
    parameters: ['story_section'],
  },
  {
    type: 'open_series_section',
    title: 'Open a Series Lab section',
    purpose: 'Open Series Lab and select Setup, Canon, Episode room, Shots or Review.',
    useWhen: 'The user asks for a specific part of Series Lab or that section helps explain the next step.',
    risk: 'read',
    parameters: ['series_section'],
  },
  {
    type: 'start_generation',
    title: 'Queue the prepared Studio job',
    purpose: 'Submit the Studio video, image, music/speech or 3D form prepared in the same turn.',
    useWhen: 'The final user message explicitly asks to generate, launch, start, queue that media, or asked for a filled example of that section.',
    risk: 'compute',
    parameters: [],
  },
  {
    type: 'create_story',
    title: 'Create a filled Story Lab draft',
    purpose: 'Create and persist a new story with overview, world, cast, locations and story beats, then show it in Story Lab.',
    useWhen: 'The user directly asks for a new story, plot or filled Story Lab example.',
    risk: 'edit',
    parameters: ['title', 'project_type', 'creative_brief', 'premise', 'logline', 'synopsis', 'theme', 'ending', 'characters', 'locations', 'outline_beats'],
  },
  {
    type: 'update_story',
    title: 'Update the active Story Lab draft',
    purpose: 'Patch the active or exactly named story, upsert named cast/locations, optionally replace its beats, preserve visual assets, and save the canonical library revision.',
    useWhen: 'The user asks to fill, revise, rename or expand an existing Story Lab project.',
    risk: 'edit',
    parameters: ['target_story_title', 'title', 'creative_brief', 'premise', 'logline', 'synopsis', 'theme', 'ending', 'genre', 'tone', 'visual_style', 'world_summary', 'language', 'characters', 'locations', 'outline_beats'],
  },
  {
    type: 'generate_story_section',
    title: 'Generate a Story Lab section proposal',
    purpose: 'Run the canonical recoverable Story Lab writer for one section or the full plan and leave its result ready for review without applying it.',
    useWhen: 'The user explicitly asks the Story Lab LLM to generate, rewrite or propose story material.',
    risk: 'compute',
    parameters: ['target_story_title', 'story_generation_scope', 'instruction', 'confirm'],
  },
  {
    type: 'apply_story_proposal',
    title: 'Apply the saved Story Lab proposal',
    purpose: 'Apply the complete recoverable proposal for the active or exactly named story, preserve visual identity references, version changed sections, and save canonical canon.',
    useWhen: 'The user explicitly asks to apply or accept the currently reviewed Story Lab proposal.',
    risk: 'edit',
    parameters: ['target_story_title', 'confirm'],
  },
  {
    type: 'approve_story_section',
    title: 'Approve a valid Story Lab section',
    purpose: 'Run the same completeness and identity checks as Story Lab, then approve the current section version and persist it canonically.',
    useWhen: 'The user explicitly asks to approve overview, world, characters, relationships or structure after review.',
    risk: 'edit',
    parameters: ['target_story_title', 'story_section', 'confirm'],
  },
  {
    type: 'approve_story_visuals',
    title: 'Attach and approve Story visual references',
    purpose: 'Resolve existing Story assets and bind approved references to the world, exact locations or exact characters, including a primary identity choice.',
    useWhen: 'The user explicitly chooses which existing images should become production references.',
    risk: 'edit',
    parameters: ['target_story_title', 'story_visual_selections', 'confirm'],
  },
  {
    type: 'generate_story_visuals',
    title: 'Generate Story concept references',
    purpose: 'Run the real recoverable Story image path for the world, exact locations, exact characters or all available visual prompts.',
    useWhen: 'The user explicitly asks to generate Story Lab concept or identity images.',
    risk: 'compute',
    parameters: ['target_story_title', 'story_visual_scope', 'target_names', 'confirm'],
  },
  {
    type: 'stage_story_comic',
    title: 'Stage a Story as a comic chapter',
    purpose: 'Use the official Story adaptation builder to replace the editable Comic Director draft, register a staged production, and open it without rendering images.',
    useWhen: 'The user explicitly asks to adapt or prepare a Story Lab project as a comic chapter.',
    risk: 'edit',
    parameters: ['target_story_title', 'direction', 'page_count', 'panels_per_page', 'confirm'],
  },
  {
    type: 'stage_story_video',
    title: 'Stage a Story film or trailer',
    purpose: 'Build the official editable film/trailer adaptation, save a reopenable production snapshot and load it into Short Film Director without rendering.',
    useWhen: 'The user explicitly asks to prepare or open a Story as a film, quick video or trailer in Director.',
    risk: 'edit',
    parameters: ['target_story_title', 'production_kind', 'direction', 'duration_seconds', 'confirm'],
  },
  {
    type: 'stage_story_music_video',
    title: 'Stage a Story music video',
    purpose: 'Select the exact Story, song/candidate and cue, save a reopenable music-video production snapshot and load Music Video Director without starting generation.',
    useWhen: 'The user explicitly asks to prepare or open a videoclip/music video from Story Lab.',
    risk: 'edit',
    parameters: ['target_story_title', 'song_name', 'cue_title', 'pacing', 'confirm'],
  },
  {
    type: 'start_director_production',
    title: 'Start a staged Story production',
    purpose: 'Start the exact Story film/trailer/music-video draft previously loaded by the Wizard, obtain its real Director pipeline ID and link it to Story production history.',
    useWhen: 'The user explicitly asks to generate or launch the film, trailer or videoclip already prepared in Director.',
    risk: 'compute',
    parameters: ['target_story_title', 'production_kind', 'confirm'],
  },
  {
    type: 'create_series_episode',
    title: 'Create a filled Series Lab episode',
    purpose: 'Find or create a series, prepare the minimum canon needed, create a filled episode outline and show Episode room.',
    useWhen: 'The user directly asks for a chapter or episode of a series. This belongs in Series Lab, not Story Lab.',
    risk: 'edit',
    parameters: ['series_title', 'series_premise', 'episode_title', 'episode_premise', 'episode_logline', 'characters', 'locations', 'outline_beats'],
  },
  {
    type: 'update_series_episode',
    title: 'Update an existing Series Lab episode',
    purpose: 'Patch the active or exactly named episode through the Series store, preserve scripts/shots/attempts/canon snapshot, and verify the canonical save.',
    useWhen: 'The user asks to revise, rename or complete an existing Series Lab episode.',
    risk: 'edit',
    parameters: ['series_title', 'target_episode_title', 'episode_title', 'episode_premise', 'episode_logline', 'outline_beats', 'target_duration_seconds'],
  },
  {
    type: 'generate_series_plan',
    title: 'Generate a recoverable Series episode plan',
    purpose: 'Start the canonical Series writer for outline, script, shots or a complete plan and surface its live recoverable job in Episode room.',
    useWhen: 'The user explicitly asks Series Lab to generate or regenerate episode planning material.',
    risk: 'compute',
    parameters: ['series_title', 'target_episode_title', 'series_plan_scope', 'instruction', 'confirm'],
  },
  {
    type: 'apply_series_plan',
    title: 'Apply a completed Series episode proposal',
    purpose: 'Resolve a completed recoverable planning job for the intended episode, apply its reviewed result through the canonical endpoint, reload and verify ownership.',
    useWhen: 'The user explicitly asks to apply or accept the completed Series Lab episode proposal.',
    risk: 'edit',
    parameters: ['series_title', 'target_episode_title', 'job_id', 'confirm'],
  },
  {
    type: 'render_series_shots',
    title: 'Render Series episode shots',
    purpose: 'Start the canonical recoverable render for selected, missing, failed or all unapproved shots and open live Render & Review.',
    useWhen: 'The user explicitly asks to render or retry episode shots after applying a shot plan.',
    risk: 'compute',
    parameters: ['series_title', 'target_episode_title', 'render_mode', 'shot_ids', 'seed', 'confirm'],
  },
  {
    type: 'review_series_attempts',
    title: 'Approve or reject Series render attempts',
    purpose: 'Approve the latest playable attempt for selected shot numbers or every eligible shot, or reject one concrete completed attempt, then open Render & Review.',
    useWhen: 'The user explicitly accepts or rejects rendered Series episode shots after reviewing them.',
    risk: 'edit',
    parameters: ['series_title', 'target_episode_title', 'review_decision', 'review_scope', 'shot_numbers', 'attempt_id', 'confirm'],
  },
  {
    type: 'assemble_series_episode',
    title: 'Join an approved Series episode',
    purpose: 'Start the recoverable ordered assembly after every shot has an approved playable output, then expose progress and download in Render & Review.',
    useWhen: 'The user explicitly asks to join, assemble or export the approved episode clips.',
    risk: 'compute',
    parameters: ['series_title', 'target_episode_title', 'confirm'],
  },
  {
    type: 'commit_series_canon',
    title: 'Commit Series episode canon decisions',
    purpose: 'Accept or reject all proposed continuity changes, or exact selected delta IDs, through optimistic canon locking.',
    useWhen: 'The user explicitly decides which proposed episode facts should affect future episodes.',
    risk: 'edit',
    parameters: ['series_title', 'target_episode_title', 'canon_decision', 'canon_item_ids', 'confirm'],
  },
  {
    type: 'open_3d_scene',
    title: 'Open an editable 3D Video scene',
    purpose: 'Resolve an exact saved scene in the active workspace, open it in Video 3D and optionally select one exact layer.',
    useWhen: 'The user explicitly asks to open a named saved 3D scene or work on one of its layers.',
    risk: 'edit',
    parameters: ['scene_name', 'layer_name', 'confirm'],
  },
  {
    type: 'save_3d_scene',
    title: 'Save the current editable 3D Video scene',
    purpose: 'Persist the currently open scene and its ordinary editable keyframes in the active workspace.',
    useWhen: 'The user explicitly asks to save the current 3D scene after editing or applying rhythm.',
    risk: 'edit',
    parameters: ['scene_name', 'confirm'],
  },
  {
    type: 'export_3d_scene',
    title: 'Render and publish the current 3D Video scene',
    purpose: 'Render every deterministic browser frame, encode the scene as MP4 and publish the verified result in Videos.',
    useWhen: 'The user explicitly asks to capture, render or export the currently open 3D scene.',
    risk: 'compute',
    parameters: ['scene_name', 'confirm'],
  },
  {
    type: 'apply_3d_rhythm',
    title: 'Apply music rhythm to an editable 3D scene layer',
    purpose: 'Open Video 3D, attach an exact existing audio output when requested, analyze BPM/beats/downbeats and bake a pulse, bounce, peek or camera-punch profile into ordinary keyframes.',
    useWhen: 'The user explicitly asks a current scene layer or camera to react to music.',
    risk: 'edit',
    parameters: ['scene_name', 'layer_name', 'audio_output_name', 'cue_source', 'rhythm_profile', 'intensity', 'confirm'],
  },
  {
    type: 'create_comic',
    title: 'Create a filled Comics draft',
    purpose: 'Create a new one- or multi-page Comics Director project with exact page stages, panels, lettering and an explicit local/MiniMax image provider. factual_biography marks a non-fiction life story. Do not draw panel art unless asked.',
    useWhen: 'The user asks for a comic, tebeo, strip, biography comic or a comic example.',
    risk: 'edit',
    parameters: ['title', 'synopsis', 'visual_style', 'language', 'characters', 'comic_pages', 'comic_panels', 'image_provider', 'model_type', 'factual_biography'],
  },
  {
    type: 'generate_comic',
    title: 'Generate comic panel artwork',
    purpose: 'Generate unfinished, failed or explicit pages of the open Comics Director plan. render_mode is missing, failed or all. page_numbers and pilot limit the batch. Local work uses the shared GPU; MiniMax uses its external API. Persist jobs per panel, resume from the first pending, cancel without losing finished art. There is no Render page button.',
    useWhen: 'The user explicitly asks to launch, draw, generate, resume, retry failed panels or render a pilot page.',
    risk: 'compute',
    parameters: ['image_provider', 'model_type', 'render_mode', 'page_numbers', 'pilot', 'biography_review', 'confirm'],
  },
  {
    type: 'generate_comic_panel',
    title: 'Regenerate one comic panel',
    purpose: 'Generate only one addressed page/panel of the open comic and replace its current artwork without touching the rest.',
    useWhen: 'The user explicitly asks to generate or regenerate a numbered panel or viñeta.',
    risk: 'compute',
    parameters: ['page_number', 'panel_number', 'confirm'],
  },
  {
    type: 'attach_studio_references',
    title: 'Attach existing image outputs to Studio',
    purpose: 'Resolve real image output names from the active workspace and attach them as a video start frame or subject/style references.',
    useWhen: 'The user asks to use one or more existing generated images as conditioning for Studio Image or Video.',
    risk: 'edit',
    parameters: ['reference_output_names', 'reference_role', 'replace_existing', 'remove_background'],
  },
  {
    type: 'configure_studio_loras',
    title: 'Configure compatible Studio LoRAs',
    purpose: 'Resolve LoRA filenames against the active model, activate them with bounded weights, and optionally replace the current set.',
    useWhen: 'The user asks to use, change or clear LoRAs in Studio Image or Video.',
    risk: 'edit',
    parameters: ['loras', 'replace_existing'],
  },
  {
    type: 'inspect_queue',
    title: 'Inspect the canonical queue',
    purpose: 'Refresh the real task list and open Activity so the user sees current jobs.',
    useWhen: 'The user asks what is in the queue, why the GPU is waiting, or the status of a job.',
    risk: 'read',
    parameters: ['queue_scope'],
  },
  {
    type: 'cancel_task',
    title: 'Cancel a canonical task',
    purpose: 'Cancel one identified active task through the canonical API after an explicit user request.',
    useWhen: 'The user clearly asks to cancel the active job or a specific task id.',
    risk: 'edit',
    parameters: ['task_id', 'confirm'],
  },
  {
    type: 'resume_task',
    title: 'Resume a canonical task',
    purpose: 'Resume one identified resumable task through the canonical API after an explicit user request.',
    useWhen: 'The user clearly asks to resume a specific interrupted or failed resumable task.',
    risk: 'edit',
    parameters: ['task_id', 'confirm'],
  },
  {
    type: 'retry_task',
    title: 'Retry a canonical task',
    purpose: 'Retry a persisted failed, cancelled or interrupted task through the canonical retry endpoint and show Activity.',
    useWhen: 'The user explicitly asks to retry a specific task or the latest failure.',
    risk: 'compute',
    parameters: ['task_id', 'confirm'],
  },
  {
    type: 'select_workspace',
    title: 'Select a workspace',
    purpose: 'Resolve an existing workspace by exact name, switch the canonical backend/store context, and keep the Wizard turn visible.',
    useWhen: 'The user asks to work in an existing named workspace.',
    risk: 'edit',
    parameters: ['workspace_name'],
  },
  {
    type: 'create_workspace',
    title: 'Create and select a workspace',
    purpose: 'Create a new isolated workspace through the canonical API, select it, and continue the Wizard conversation there.',
    useWhen: 'The user explicitly asks to create a new named workspace.',
    risk: 'edit',
    parameters: ['workspace_name'],
  },
]

export function buildAgentCapabilityGuide(): string {
  return AGENT_CAPABILITIES.map(capability => (
    `- ${capability.type} [${capability.risk}]: ${capability.purpose} `
    + `Use when: ${capability.useWhen} Parameters: ${capability.parameters.join(', ') || 'none'}.`
  )).join('\n')
}
