export const DARK_LIVING_IDS = [
  'dark-living-sleeping-titan',
  'dark-living-bell-of-ash',
  'dark-living-antler-moon',
  'dark-living-drowned-king',
  'dark-living-red-pilgrim',
  'dark-living-last-aqueduct',
  'dark-living-ember-heart',
  'dark-living-violet-oracle',
  'dark-living-winter-shoulder',
  'dark-living-thorn-crown',
  'dark-living-black-tide',
  'dark-living-golden-ruin',
  'dark-living-hollow-saint',
  'dark-living-fungal-throne',
  'dark-living-storm-bridge',
  'dark-living-sand-library',
  'dark-living-jade-dragon',
  'dark-living-moon-grave',
  'dark-living-copper-trees',
  'dark-living-final-gate',
] as const
