import { expect, test } from '@playwright/test'
import { closeApp, gotoApp } from '../helpers/gotoApp'

test('generation survives reload and shared review regenerates only the chosen shot', async ({ page }) => {
  const server = process.env.HOCUS_PRODUCTION_TEST_API_URL
  test.skip(!server, 'Requires the isolated productionApiServer.py; no GPU or user server is used.')
  const session = await gotoApp(page)
  await page.route('**/api/v1/production-projects**', async route => {
    const incoming = new URL(route.request().url())
    const response = await route.fetch({ url: `${server}${incoming.pathname}${incoming.search}` })
    await route.fulfill({ response })
  })
  await page.route('**/api/v1/music-productions/**', async route => {
    const incoming = new URL(route.request().url())
    const response = await route.fetch({ url: `${server}${incoming.pathname}${incoming.search}` })
    await route.fulfill({ response })
  })
  const start = await page.request.post(`${server}/test/start`)
  expect(start.ok()).toBe(true)
  const started = await start.json()
  expect(started.result.project.kind).toBe('story')
  await expect.poll(async () => (await (await page.request.get(`${server}/test/state`)).json())['browser-clip.shots.json']?.shots.length).toBe(2)
  await page.reload()
  await page.getByRole('button', { name: 'Production', exact: true }).click()
  await page.getByRole('tab', { name: 'Works', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Browser journey', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Review shots', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Review shots' })
  await expect(dialog).toBeVisible()
  await expect(dialog.locator('video')).toHaveCount(2)
  const first = dialog.locator('ol > li').first()
  const second = dialog.locator('ol > li').nth(1)
  await first.getByRole('button', { name: 'Regenerate', exact: true }).click()
  await expect(first.getByText('new.mp4', { exact: true })).toBeVisible()
  await expect(first.getByText('old.mp4', { exact: true })).toBeVisible()
  await expect(second.getByText('other.mp4', { exact: true })).toBeVisible()
  await first.getByRole('button', { name: 'Approve', exact: true }).click()
  await first.getByRole('button', { name: 'Lock', exact: true }).click()
  await expect(first.getByRole('button', { name: /Regenerate/ })).toBeDisabled()
  const disk = await (await page.request.get(`${server}/test/state`)).json()
  expect(Object.keys(disk['.story-library-v1.json'].projects)).toHaveLength(1)
  expect(disk['browser-clip.review.json'].shots.s1.status).toBe('approved')
  expect(disk['browser-clip.shots.json'].shots[1].clip).toBe('other.mp4')
  await closeApp(page, session)
})
